[package]
name = "compiler"
version = "0.1.0"
authors = ["Dmitry <mamhigtt@gmail.com>"]
edition = "2018"

[dependencies]
llvm-sys = "100"
libc = "0.2.80"
clap = "2.33.3"
sana = "0.1.1"
itertools = "0.9.0"
traversal = "0.1.2"


